#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftwheels,    tmotorVex393_HBridge, openLoop, reversed, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port10,          rightwheels,   tmotorVex393_HBridge, openLoop, driveRight, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(1000);
	float diamaterOfWheel = 2.125;
	float circumference = diamaterOfWheel*PI;

	int distanceToGo = 12;
	float rotations = distanceToGo/circumference;
	int degreesToTurn = rotations*360;

	nMotorEncoder[leftwheels] = 0;
	nMotorEncoder[rightwheels] = 0;

//go forward 3 feet
while(nMotorEncoder[leftwheels] < 1000){
	motor[leftwheels] = 50;
	motor[rightwheels] = 50;
}
motor[leftwheels] = 0;
motor[rightwheels] = 0;
//turn left 90deg
nMotorEncoder[leftwheels] = 0;
nMotorEncoder[rightwheels] = 0;
wait1Msec(1000);
while(nMotorEncoder[rightwheels] < 350){
	motor[leftwheels] = -50;
	motor[rightwheels] = 50;
}
stopAllTasks();
//go forward 4 feet
//turn right 90deg
//go forward 3 feet
//turn right 90deg
//go forward 5 feet


}
